import json
import logging

from agent.llm import get_llm
from agent.state import AgentState

logger = logging.getLogger(__name__)

REFLECT_PROMPT = """You are reviewing a patch generated by an AI agent.

ORIGINAL ISSUE:
{issue}

GENERATED PATCH:
{patch}

EXECUTION RESULT:
Tests passed: {tests_passed}
{passed}/{total} tests passed
Output:
{output}

Evaluate the patch strictly:
1. Did it fix the stated issue?
2. Is it minimal?
3. Did the tests pass?
4. Could it introduce regressions?

Respond ONLY with valid JSON:
{{
  "decision": "APPROVE" or "REJECT",
  "reason": "One sentence explanation.",
  "confidence": 0.0
}}"""


def evaluate_node(state: AgentState) -> dict:
    exec_result = state["execution_result"]
    prompt = REFLECT_PROMPT.format(
        issue=state["current_issue"],
        patch=state["current_patch"],
        tests_passed=exec_result.get("tests_passed"),
        passed=exec_result.get("passed_tests", 0),
        total=exec_result.get("total_tests", 0),
        output=exec_result.get("output", "")[:1000],
    )

    response = get_llm().invoke(prompt)
    verdict = _parse_json_response(response.content)
    approved = verdict.get("decision") == "APPROVE" and exec_result.get(
        "tests_passed", False
    )
    escalate = not approved and state["iteration"] >= state["max_iterations"]

    logger.info(
        "Evaluation verdict: %s (%s)",
        verdict.get("decision"),
        verdict.get("reason"),
    )
    return {"approved": approved, "escalate": escalate}


def _parse_json_response(raw_content: str) -> dict:
    try:
        return json.loads(raw_content)
    except json.JSONDecodeError:
        import re

        match = re.search(r"\{.*\}", raw_content, re.DOTALL)
        if not match:
            return {"decision": "REJECT", "reason": "parse error", "confidence": 0.0}
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            return {"decision": "REJECT", "reason": "parse error", "confidence": 0.0}
